fix: useModal return type error  #833
DouyinFE/semi-design pull request #836
Opened 2022-05-16 06:47 UTC by DaiQiangReal

[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [x] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update
 - [ ] Refactor
 - [ ] Test Case
 - [ ] TypeScript definition update
 - [ ] Document improve
 - [ ] CI/CD improve
 - [ ] Branch sync
 - [ ] Other, please describe:

### PR description

Fixes #

### Changelog
🇨🇳 Chinese
- Fix: 修复 useModal typescript 返回类型不严谨的问题

---

🇺🇸 English
- Fix: Fix the problem that the return type of useModal typescript is not strict

### Checklist
- [x] Test or no need
- [ ] Document or no need
- [ ] Changelog or no need

### Other
- [ ] Skip Changelog

### Additional information

2022-05-16 06:50 UTC, pointhalo commented on packages/semi-ui/modal/useModal/index.tsx
> +export default function useModal(): [{ info: (config: ModalReactProps) => { destroy: () => void, update: (newConfig: ConfirmProps) => void }, success: (config: ModalReactProps) => { destroy: () => vo
这么长不换个行吗，看起来太费劲了

2022-05-16 08:36 UTC, DaiQiangReal commented on packages/semi-ui/modal/useModal/index.tsx
> +export default function useModal(): [{ info: (config: ModalReactProps) => { destroy: () => void, update: (newConfig: ConfirmProps) => void }, success: (config: ModalReactProps) => { destroy: () => vo
更新了

2022-05-16 10:45 UTC, tianenpang requested changes

2022-05-16 10:45 UTC, tianenpang commented on packages/semi-ui/modal/useModal/index.tsx
> +    confirm: (config: ModalReactProps) => { destroy: () => void, update: (newConfig: ConfirmProps) => void }
一个相关的问题：`ConfirmProps` 中的 `type` 由于不是可选属性，在 `modal.update` 时会提示 `Property 'type' is missing in type`，可能需要再处理下 🤔

![model update-type-issue](https://user-images.githubusercontent.com/32772271/168576020-bc996f6c-e46b-4225-aa1c-ce18ca283169.png)

2022-05-17 06:52 UTC, DaiQiangReal commented on packages/semi-ui/modal/useModal/index.tsx
> +export default function useModal(): [{
resolve

2022-05-17 06:53 UTC, DaiQiangReal commented on packages/semi-ui/modal/useModal/index.tsx
> +    confirm: (config: ModalReactProps) => { destroy: () => void, update: (newConfig: ConfirmProps) => void }
> 一个相关的问题：`ConfirmProps` 中的 `type` 由于不是可选属性，在 `modal.update` 时会提示 `Property 'type' is missing in type`，可能需要再处理下
> 
> ![model update-type-issue](https://user-images.githubusercontent.com/32772271/168576020-bc996f6c-e46b-4225-aa1c-ce18ca283169.png)
> 
> 目前在非“确认模态对话框”时配置类型依然可以改变其类型
> 
> ![modal-type](https://user-images.githubusercontent.com/32772271/168580653-18757536-3b48-45db-80c7-193a60432559.png)
> 
> 建议按以下类型约束会不会好些 🤔 `info, success, error, warning` 的 `update` 参数类型为 `ModalReactProps`
> 
> `confirm` 的 `update` 参数类型为 `ConfirmProps` 且 `type` 可选

可以再看下，刚加了泛型判断

2022-05-23 09:32 UTC, merged